### ISSUE TITLE
Embedding Dataset Usage Details

### ISSUE THREAD

**Issue by gopikrishnajha** [facebookresearch/dlrm_datasets#4]
First of all, thanks for this much-needed dataset. Can you explain the following?
- How is the dataset organized and how to use it? Does one pt file correspond to one embedding table? Does a pt file contain the embedding information or it has MLP info as well?
- How to load the pt files to get the indices and offsets to the embedding tables?
- Is there any straightforward way to integrate this with the DLRM code?

**Comment by mdschatz** [comment]
Hi @gopikrishnajha, sure thing.

- How is the dataset organized and how to use it? Does one pt file correspond to one embedding table? Does a pt file contain the embedding information or it has MLP info as well?

Each dataset is defined by a pt file that comprises a fixed number of tables and batch size that is specified in the file name (i.e. they should follow the convention of `*_t<num_tables>_bs<batch_size>`).  Reading each of these files into PyTorch provides the Indices and Offsets tensors that are inputs to the embedding bag operation; the corresponding Lengths tensor is provided as well; however, it is just a repackaging of the Offsets tensor.

At this time, we do not provide MLP information with these datasets as the performance of these components are not as affected by the input's data values.  Providing this sort of data is something we are considering doing; however, for now we are primarily focused with making available representative datasets for the less structured layers first.  I'll be sure to call out any updates on this as we move forward.

- How to load the pt files to get the indices and offsets to the embedding tables?

Sorry for this not being initially available.  We have updated our README to include instructions on how to read this data in both PyTorch as well as in the [FBGemm](https://github.com/pytorch/FBGEMM) library for system benchmarking.  This should cover the functionality for the initial use-cases we had in mind; however, there are more places that need to be hooked up as you mention.

- Is there any straightforward way to integrate this with the DLRM code?

This is next on my list of things to do for this project.  I recognize that it may be a little confusing that this support isn't already there considering the naming.  This is because our primary motivation was to expose details that influence hardware performance on a training iteration-by-iteration basis first instead of full training.  I will send an update once the DLRM ingestion support is added.

Thanks for the great questions and please let us know if you have any others!

**Comment by gopikrishnajha** [comment]
Thanks, @mdschatz for the explanation. It was very helpful.

A couple of more questions.
1. Is the number of tables the same as the number of categorical features? What is the size of embedding vectors (m) and the number of vectors per table (n)? We would need to initialize num_table number of embedding tables each of m x n dimensions, right? 
2. Can you explain the purpose of the lengths tensor? I can't understand why is this tensor required.
3. I noticed that ```offsets.shape``` returns 56098817 for ```fbgemm_t856_bs65536_0.pt```, which is 1 more than ```num_tables x batch_size```. What is this one extra value for?

**Comment by yifanliu112** [comment]
Hi @gopikrishnajha,

1. Yes, the number of tables is the number of categorical/sparse features. Since the embedding vectors themselves and their dimensions are not the focus of this dataset, thus they are not provided. But just for your information, each embedding table could have a different dimension and number of vectors (that is, instead of `m` and `n`, it makes more sense to denote them as `m_i` and `n_i`, where the subscription is for individual tables). With the current dataset, you **can** estimate the number of vectors per table (`n_i`) with the largest index value of that table, but you probably won't get further beyond that. We are having a discussion on if we should and how to synthesize the embedding tables (or some of their characteristics statistics) beside their access patterns. Let us know if you have particular use cases for it so it helps us prioritize.

2. The lengths tensor is just a simple transformation of the offsets tensor, as explained in README. It is just provided for validation, and you're right that it is not strictly required since the offsets tensor together with the number of tables and batch size contains the same information.

3. An additional 0 is prepended to the offsets tensor, that's why it is 1 larger than `num_tables x batch size`.

**Comment by mdschatz** [comment]
Just following up on Yifan's response regarding the lengths and offsets tensor:

2&3.  As Yifan pointed out, the offsets tensor is just an alternate representation of the lengths tensor that denotes how the input vectors should be accumulated to form the output vectors.  Offsets are provided in addition to Lengths so that PyTorch's nn.EmbeddingBag operator can work with this dataset directly and benefit from the preferred layout.  We provided both in this dataset for validation purposes as it can be difficult to know how to index into the offsets tensor since it represents two dimensions; the Lengths tensor should make the organization clearer as the values in the Offsets need to conform to the values in the Lengths tensor.

**Comment by gopikrishnajha** [comment]
@yifanliu112 
w.r.t. your comment _"you can estimate the number of vectors per table (n_i) with the largest index value of that table"_, how is index tensor divided/organized across tables. ```index``` is a 1d tensor, and unless we know how values for different tables are placed in this tensor, we can not figure out n_i for individual tables.

@mdschatz 
w.r.t your comment _"Offsets are provided in addition to Lengths so that PyTorch's nn.EmbeddingBag operator can work with this dataset directly and benefit from the preferred layout."_, In my understanding, ```nn.EmbeddingBag``` should be initialized on a per-table basis, shouldn't we have ```num_tables``` number of ```indices``` tensors, or at least some way to break the current 1d ```indices``` tensor into ```num_tables``` chunks? 

Even if we initialize all tables into one monolithic ```nn.EmbeddingBag``` embedding table, how does the current ```indices``` tensor distinguish between nth (say 0th) index of two different embedding tables?

**Comment by mdschatz** [comment]
@gopikrishnajha,

You're correct that EmbeddingBag only works on individual tables while this dataset provides numerous tables together.  My apologies for being a bit loose with my statement as in order to apply the nn.EmbeddingBag operation requires splitting off the individual table indices and offsets from the dataset.  The comment was meant to inform that offsets are provided specifically to align with the nn.EmbeddingBag interface which accepts offsets over lengths.  The most direct way to use this dataset is via the [`batch_benchmark_run.py`](https://github.com/pytorch/FBGEMM/tree/main/fbgemm_gpu/bench/scripts) script provided in the FBGEMM library.

Using the nn.EmbeddingBag operator will require slicing the indices vector according to the offsets you're interested in addition to re-zeroing the subset of the offsets tensor you're interested in.

To your second question regarding the order of entries in `offsets`, the offsets order table entries after one another.  Therefore, as lengths is a `num_table x batch_size` tensor, you can expect entries in `offsets` to order the second dimension (batch) contiguously and first dimension (tables) separated by a stride of `batch_size` entries.

I hope this helps.

**Comment by usajid14** [comment]
Hi, first of all, thank you for providing this dataset. Few quick questions:

1) What is the difference between fbgemm_t856_bs65536.pt and other indexed files (e.g. fbgemm_t856_bs65536_0.pt)? Is that only about total # of indices?

2) Can we consider these independent and indexed files (fbgemm_t856_bs65536_0.pt, fbgemm_t856_bs65536_1.pt, .... fbgemm_t856_bs65536_15.pt) as consecutive files/batches? If not, are they ordered yet by their number-wise?

Thanks.

**Comment by yifanliu112** [comment]
Hi @usajid14,

1. Technically, there is no difference between `fbgemm_t856_bs65536.pt` and other indexed files. We just generated them in two separate runs.
2. `fbgemm_t856_bs65536.pt` and other indexed files can be considered as independent batches of one training dataset. They are not arranged in any particular order.

Please let us know if you have other questions.

**Comment by usajid14** [comment]
@yifanliu112 Thank you for your reply. Can we also assume the same memory access pattern for the testing purpose?

**Comment by yifanliu112** [comment]
> @yifanliu112 Thank you for your reply. Can we also assume the same memory access pattern for the testing purpose as seen in the given workload?

Hi @usajid14, can you be more specific on what you meant by "testing purpose"?

**Comment by yifanliu112** [comment]
Close this issue due to inactivity.
